# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "kanaschool"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-12"
compatibility_flags = [
	"nodejs_compat",
	"nodejs_als"
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
run_worker_first = [ "/api/*" ]
not_found_handling = "none"

[observability]
enabled = true

[[d1_databases]]
binding = "D1_DB"
database_name = "kanaschool-d1-prod"
database_id = "99ae80c8-45bf-49fa-b01d-d565f7bcab4e"
migrations_dir = "migrations"
